module.exports = {
  content: ["./Front-end/modules/**/*.php"],
  theme: {
    extend: {
      colors: {
        primary: "#2a83e9",
        "primary-dark": "#1544b7",
        secondary: "#1544b7",
        "blue-primary": "#2a83e9",
        "primary-dark-color": "#1544b7",

        "background-light": "#f5f7f8",
        "background-dark": "#0f1923",
        surface: "#f9f9ff",
        background: "#f9f9ff",

        "shopee-gray": "#f5f5f5",
        "shopee-success": "#26aa99",

        "surface-container-high": "#e6e8f0",
        "primary-container": "#2a83e9",
        "primary-fixed": "#e0efff",
        "on-secondary-container": "#00226e",
        "secondary-container": "#668afe",
        "inverse-on-surface": "#eff0f9",
        "on-primary-fixed-variant": "#1544b7",
        "surface-container": "#ecedf6",
        "on-primary-fixed": "#001b3c",
        "on-surface": "#191c22",
        "on-background": "#191c22",
        "on-tertiary-fixed-variant": "#713700",
        "inverse-surface": "#2d3037",
        "secondary-fixed-dim": "#b6c4ff",
        "tertiary-fixed-dim": "#ffb784",
        "surface-container-low": "#f2f3fc",
        "primary-fixed-dim": "#a7c8ff",
        outline: "#717784",
        "on-surface-variant": "#414753",
        "surface-bright": "#f9f9ff",
        tertiary: "#914800",
        "on-secondary": "#ffffff",
        "outline-variant": "#c1c6d5",
        "tertiary-fixed": "#ffdcc6",
        "on-secondary-fixed-variant": "#013baf",
        "surface-variant": "#e1e2ea",
        "surface-tint": "#2a83e9",
        "on-tertiary-fixed": "#301400",
        "on-error-container": "#93000a",
        "surface-dim": "#d8dae2",
        "on-secondary-fixed": "#00164f",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#fffbff",
        "on-error": "#ffffff",
        "on-primary-container": "#fefcff",
        "on-primary": "#ffffff",
        error: "#ba1a1a",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e1e2ea",
        "tertiary-container": "#b65c00",
        "secondary-fixed": "#dce1ff",
        "inverse-primary": "#a7c8ff",
        "surface-container-lowest": "#ffffff",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
};
